### ISSUE TITLE
Example config of Clash Preimu

### ISSUE THREAD

**Issue by tomatopunk** [privacy-protection-tools/anti-AD#458]
```

rule-providers:
  anti_ad:
    type: http
    behavior: domain
    url: "https://anti-ad.net/clash.yaml"
    path: ./ruleset/anti_ad.yaml
    interval: 86400

rules:
  - RULE-SET,anti_ad,REJECT
# or use proxy-groups:

proxy-groups:
   - name: 🌚anti-AD
    type: select
    proxies:
      - DIRECT
      - REJECT
     
rules:
  - RULE-SET,anti_ad,🌚anti-AD
```

![image](https://user-images.githubusercontent.com/40015047/124593084-ccf1fd00-de90-11eb-9314-842e799cf4fd.png)
