### ISSUE TITLE
[新增数据格式]是否可以考虑支持 mosdns

### ISSUE THREAD

**Issue by luzhaohui** [privacy-protection-tools/anti-AD#660]
看到有支持 SmartDNS 的数据格式，能否考虑支持 mosdns？👇

[mosdns](https://github.com/IrineSistiana/mosdns)

**Comment by luzhaohui** [comment]
> 我觉得还是smartdns好用，mosdns怎么设置都上不了网

这是你的个人问题，与本话题无关。

**Comment by hacamer** [comment]
> 看到有支持 SmartDNS 的数据格式，能否考虑支持 mosdns？👇
> 
> [mosdns](https://github.com/IrineSistiana/mosdns)

看了，似乎没看明白，有实例不？

**Comment by luzhaohui** [comment]
> > 看到有支持 SmartDNS 的数据格式，能否考虑支持 mosdns？👇
> > [mosdns](https://github.com/IrineSistiana/mosdns)
> 
> 看了，似乎没看明白，有实例不？

mosdns 的 [wiki](https://irine-sistiana.gitbook.io/mosdns-wiki/)
数据格式 [V2Ray 路由规则文件](https://github.com/Loyalsoldier/v2ray-rules-dat)，解析 geosite.dat 中的 geosite:category-ads-all 类别。

**Comment by hacamer** [comment]
> > > 看到有支持 SmartDNS 的数据格式，能否考虑支持 mosdns？👇
> > > [mosdns](https://github.com/IrineSistiana/mosdns)
> > 
> > 
> > 看了，似乎没看明白，有实例不？
> 
> mosdns 的 [wiki](https://irine-sistiana.gitbook.io/mosdns-wiki/) 数据格式 [V2Ray 路由规则文件](https://github.com/Loyalsoldier/v2ray-rules-dat)，解析 geosite.dat 中的 geosite:category-ads-all 类别。

https://github.com/Loyalsoldier/v2ray-rules-dat
就是这个项目的geosite.dat文件对吧
https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
这个里面的
geosite:category-ads-all类别
咱弄就是只输出geosite:category-ads-all这个类别到geosite.dat
对吧？

**Comment by luzhaohui** [comment]
> > > > 看到有支持 SmartDNS 的数据格式，能否考虑支持 mosdns？👇
> > > > [mosdns](https://github.com/IrineSistiana/mosdns)
> > > 
> > > 
> > > 看了，似乎没看明白，有实例不？
> > 
> > 
> > mosdns 的 [wiki](https://irine-sistiana.gitbook.io/mosdns-wiki/) 数据格式 [V2Ray 路由规则文件](https://github.com/Loyalsoldier/v2ray-rules-dat)，解析 geosite.dat 中的 geosite:category-ads-all 类别。
> 
> https://github.com/Loyalsoldier/v2ray-rules-dat 就是这个项目的geosite.dat文件对吧 https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat 这个里面的 geosite:category-ads-all类别 咱弄就是只输出geosite:category-ads-all这个类别到geosite.dat 对吧？

Yes，有了这个的话，用 mosdns 的小伙伴就可以非常方便的用上 anti-AD 了。

**Comment by hacamer** [comment]
> > > > > 看到有支持 SmartDNS 的数据格式，能否考虑支持 mosdns？👇
> > > > > [mosdns](https://github.com/IrineSistiana/mosdns)
> > > > 
> > > > 
> > > > 看了，似乎没看明白，有实例不？
> > > 
> > > 
> > > mosdns 的 [wiki](https://irine-sistiana.gitbook.io/mosdns-wiki/) 数据格式 [V2Ray 路由规则文件](https://github.com/Loyalsoldier/v2ray-rules-dat)，解析 geosite.dat 中的 geosite:category-ads-all 类别。
> > 
> > 
> > https://github.com/Loyalsoldier/v2ray-rules-dat 就是这个项目的geosite.dat文件对吧 https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat 这个里面的 geosite:category-ads-all类别 咱弄就是只输出geosite:category-ads-all这个类别到geosite.dat 对吧？
> 
> Yes，有了这个的话，用 mosdns 的小伙伴就可以非常方便的用上 anti-AD 了。

我去研究一下

**Comment by xlighting2017** [comment]
> > > > > 看到有支持 SmartDNS 的数据格式，能否考虑支持 mosdns？👇
> > > > > [mosdns](https://github.com/IrineSistiana/mosdns)
> > > > 
> > > > 
> > > > 看了，似乎没看明白，有实例不？
> > > 
> > > 
> > > mosdns 的 [wiki](https://irine-sistiana.gitbook.io/mosdns-wiki/) 数据格式 [V2Ray 路由规则文件](https://github.com/Loyalsoldier/v2ray-rules-dat)，解析 geosite.dat 中的 geosite:category-ads-all 类别。
> > 
> > 
> > https://github.com/Loyalsoldier/v2ray-rules-dat 就是这个项目的geosite.dat文件对吧 https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat 这个里面的 geosite:category-ads-all类别 咱弄就是只输出geosite:category-ads-all这个类别到geosite.dat 对吧？
> 
> Yes，有了这个的话，用 mosdns 的小伙伴就可以非常方便的用上 anti-AD 了。

https://github.com/Loyalsoldier/v2ray-rules-dat

这里有现成的，fork it，在 action 里面 加上从 本repo 获取的 域名txt （[anti-ad-domains.txt](https://github.com/privacy-protection-tools/anti-AD/blob/master/anti-ad-domains.txt)） ，
<img width="670" alt="image" src="https://user-images.githubusercontent.com/25970065/179391322-eb5462fd-c836-4a8a-857f-5f12d622ec0a.png">
然后让 action自己跑起来，就能得到 geosite.dat了吧

主要是 geosite 不止包含 anti-ad， 假设在本repo生成 geosite，如果又缺了其他的部分， 要咋办呢(比如 有人希望是  GFW模式，有人希望是 白名单模式， 而他们都希望控制文件size)

**Comment by xlighting2017** [comment]
又多看了一眼。。。  mosdns 本身就支持 txt domain文件， 不用  geosite 也可以

直接下载本repo 的  [anti-ad-domains.txt](https://github.com/privacy-protection-tools/anti-AD/blob/master/anti-ad-domains.txt)  （不确定是否要移除最前面的几行注释，请自行尝试）

然后 mosdns 的配置文件里面 指定该文件为 data_providers , 接着匹配 广告域名， 加入运行逻辑， 搞定
```
data_providers:
  - tag: anti-AD
    file: ./anti-ad-domains.txt
    auto_reload: true

.....

  # 匹配广告域名的插件
  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - 'provider:anti-AD'
....

  # 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，
  # 否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:
      exec:
        # 缓存
        - cache

        # 屏蔽广告域名
        - if: query_is_ad_domain
          exec:
            - _new_nxdomain_response
            - _return
....
```
