### ISSUE TITLE
能否为Clash添加Text格式的规则

### ISSUE THREAD

**Issue by svngxr** [privacy-protection-tools/anti-AD#863]
能否考虑添加Text格式的Clash规则。和Surge一样，Clash的text格式比classical性能更好。

希望除了anti-ad-clash.yaml之外，能添加一个anti-ad-clash.txt

非常感谢

规则的格式类似：
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Domain_For_Clash.txt

**Comment by DustinWin** [comment]
不是可以直接用吗？
```
rule-providers:
  anti-ad:
    type: http
    # 不是 classical
    behavior: domain
    url: "https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml"
    path: ./ruleset/anti-ad.yaml
    interval: 86400
```
